plugins {
	id 'groovy'
	id 'org.jetbrains.intellij.platform' version '2.18.1'
	id 'com.diffplug.spotless' version '8.8.0'
}

ext.pitVersion = '1.20.0'
ext.pitJunit5PluginVersion = '1.2.3'

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}


// workaround for http://issues.gradle.org/browse/GRADLE-2538
sourceSets.main.java.srcDirs = []
sourceSets.main.groovy.srcDir 'src/main/java'

repositories {
	mavenCentral()
	mavenLocal()
	intellijPlatform {
		defaultRepositories()
	}
}


dependencies {
	intellijPlatform {
		intellijIdea('2024.3')
		bundledPlugin('com.intellij.java')
		testFramework(org.jetbrains.intellij.platform.gradle.TestFrameworkType.Platform.INSTANCE)
	}
	implementation("org.pitest:pitest-command-line:$pitVersion") { transitive = false }
	implementation("org.pitest:pitest-entry:$pitVersion") { transitive = false }
	implementation("org.pitest:pitest:$pitVersion") { transitive = false }
	implementation "org.pitest:pitest-junit5-plugin:$pitJunit5PluginVersion"
	implementation 'org.apache.commons:commons-text:1.10.0'
	implementation('org.junit.platform:junit-platform-launcher:1.9.2') { transitive = false }
	compileOnly 'org.codehaus.groovy:groovy-all:3.0.19'
	testCompileOnly 'org.codehaus.groovy:groovy-all:3.0.19'
	testImplementation('org.spockframework:spock-core:2.3-groovy-3.0') {
		exclude group: 'org.codehaus.groovy'
	}
	testImplementation 'junit:junit:4.13.2'
	testImplementation 'net.bytebuddy:byte-buddy:1.14.11'
	testImplementation 'org.objenesis:objenesis:3.3'
}

jar {
	metaInf {
		from('META-INF') {
			include 'plugin.xml'
			include 'pluginIcon.svg'
		}
	}
}

test {
	useJUnitPlatform()
}

tasks.named('prepareTestSandbox') {
	exclude('**/spock-core*')
	exclude('**/spock*')
	exclude('**/testFramework*')
}

wrapper {
	gradleVersion "9.6.1"
}

spotless {
	java {
		palantirJavaFormat()
	}
	groovy {
		greclipse()
		excludeJava()
	}
	groovyGradle {
		target '*.gradle'
		greclipse()
	}
}